spring.application.name=api-gateway

server.port=8082

# config do Eureka Client (do Gateway)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Endereço do Eureka Server (defaultZone é camelCase)
# localhost 8761, onde o Eureka Server está recebendo as requisições
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Discovery Locator (rotas dinâmicas via Eureka)
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# Converte o ID dos serviços registrados no Eureka
# para minúsculas ao criar rotas dinâmicas
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true