spring.application.name=ms-pagamento

spring.profiles.active=test
spring.jpa.open-in-view=false

# Eureka Client: registra no Eureka Server e busca o catálogo (registry)

# config do Eureka Client (ms-pedido)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Endereço do Eureka Server (defaultZone é camelCase)
# localhost 8761, onde o Eureka Server está recebendo as requisições
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Porta aleatória para permitir múltiplas instâncias (escala local)
server.port=0

# Identificador da instância (evita sobrescrever no registry)
eureka.instance.instance-id=${spring.application.name}:${random.int[1,99]}

#Circuit Breaker: monitora as últimas 3 chamadas
resilience4j.circuitbreaker.instances.atualizarPedido.slidingWindowSize=3

# Tipo da janela: por quantidade de chamadas
# COUNT_BASED = ultimas N chamadas
# TIME_BASED = últimos N segundos
resilience4j.circuitbreaker.instances.atualizarPedido.slidingWindowType=COUNT_BASED

# So começa a calcular taxa de falha após pelo menos 2 chamadas
resilience4j.circuitbreaker.instances.atualizarPedido.minimumNumberOfCalls=2

# Abre o circuito quando a taxa de falhas atingir 50%
resilience4j.circuitbreaker.instances.atualizarPedido.failureRateThreshold=50

# Tempo que o circuito permanece OPEN antes de ir para HALF_OPEN
resilience4j.circuitbreaker.instances.atualizarPedido.waitDurationInOpenState=50s

# Em HALF_OPEN, permite 2 chamadas de teste
resilience4j.circuitbreaker.instances.atualizarPedido.permittedNumberOfCallsInHalfOpenState=2