spring.application.name=eureka-server

# Eureka Server (Service Registry)
# - centraliza o catálogo de instâncias (endereços/metadados) parar discovery
# - o próprio server NÃO deve se registrar nem buscar o registry como cliente.

# porta do servidor
server.port=8761

# Server não registar a si mesmo no Eureka
eureka.client.register-with-eureka=false

# Server não precisa buscar o registry
eureka.client.fetch-registry=false

# Versão recomendada (evita erro ao trocar porta)
# defaultZone precisa ser exatamente assim (camelCase), pois serviceUrl é um Map
eureka.client.serviceUrl.defaultZone=http://localhost:${server.port}/eureka/